### ISSUE TITLE
Increase CDR Plugin OVA/AMI protection

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#1]
@MaNe2020 commented on [Fri May 14 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/348)

To ssh to CDR Plugin we are now use username/pass both being plain username and plain password, kind of obvious. 
We need to change this, start using pem key or bastion or harder passwords. 

---

@GINAGC commented on [Fri May 14 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/348#issuecomment-841230713)

@pranaysahith can you take a look to this please?

---

@pranaysahith commented on [Fri May 14 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/348#issuecomment-841253474)

@GINAGC  @MaNe2020  we can add a github secret "SSH_PASSWORD" in the repo with a strong password and packer will automatically use it during build.

**Comment by MaNe2020** [comment]
@pranaysahith lets do as you suggested. @GINAGC pls confirm

**Comment by GINAGC** [comment]
@pranaysahith yes, lets do that please.

**Comment by pranaysahith** [comment]
@MaNe2020 @GINAGC  could you please ask Dinis to add the secret `SSH_PASSWORD` with a strong password?

**Comment by kekesimarti** [comment]
@DinisCruz FYI

**Comment by GINAGC** [comment]
Password updated, please check.

**Comment by MaNe2020** [comment]
@GINAGC run git actions: https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/2710505338?check_suite_focus=true and tested on that new AMI.
Password seems to be the same as before.
Let me know if this should be tested somewhat differently

**Comment by GINAGC** [comment]
@MaNe2020 please test and close after testing.

**Comment by MaNe2020** [comment]
@pranaysahith pls add new pass to passbolt and share.
I just deployed new AMI. Password is changed but I do not know what is the new one.

**Comment by MaNe2020** [comment]
Password is added and shared with the team. 
As this is already part of the release and new AMI, will close it.
