### ISSUE TITLE
File Analysis dashboard opens without loading file results

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#11]
@kekesimarti commented on [Fri May 07 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/302)

![image](https://user-images.githubusercontent.com/79467690/117427127-fe982780-af24-11eb-8caf-52692116ffc0.png)
Getting the same picture after clear data, load files and start processing as well:
![image](https://user-images.githubusercontent.com/79467690/117427244-225b6d80-af25-11eb-92b3-9b7fa9f2b15b.png)

**Comment by MaNe2020** [comment]
Cannot reproduce this one but it can happen due to indexes not being loaded.

**Comment by MaNe2020** [comment]
This is valid issue but not sure about exact steps to reproduce it.
I had scenario-1000 processed and set scenario-2000 as default, set IPs and load data. On loading data dashboard stayed empty.

**Comment by MaNe2020** [comment]
I haven't seen this one for a while.
Will close it as we have other dashboard issues to work on. @chrisdiao

**Comment by MaNe2020** [comment]
@dpatel7 pls leave the comment of how to reproduce this as you are reopening it.
