### ISSUE TITLE
Consume these metrics from python and support to the F2F Plugin to extract status data from it

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#13]
@kekesimarti commented on [Mon May 10 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/317)

- make sure that the pod is running on a different port
- make that officially supported since that set of metrics is really powerful (see pic) http://34.253.226.108:8080/metrics

Try [Prometheus](https://github.com/prometheus/client_python)

This bug is still happening in some of the servers (i.e. the metrics pod is still competing with the Rest API for the port 8080)
I found it on the cdr-plugin-dev-minio-sdk-asg server from the autoscaling group.
![image](https://user-images.githubusercontent.com/79467690/117637269-eec94f00-b181-11eb-867f-12bb371d6633.png)
![image](https://user-images.githubusercontent.com/79467690/117637317-fab51100-b181-11eb-9ad0-ade46c485eb1.png)
![image](https://user-images.githubusercontent.com/79467690/117637389-0bfe1d80-b182-11eb-8700-2149d1e719b4.png)

**Comment by ggrig** [comment]
@GINAGC 
This is about consuming Kubernetes metrics from cdr-plugin
However, we do not currently run it in Kubernetes. It still is docker-compose
So we probably should consider this as collecting docker metrics with Prometheus (as per https://docs.docker.com/config/daemon/prometheus/). That currently is implemented with metrics API on the swagger page.
