### ISSUE TITLE
Would be good if everything can be done on Workflow page 

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#14]
@kekesimarti commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/332)

To set IPs we need first to go to f2f page and set base dir, then go to set IPs page and if we now go back to f2f it will show the previous dir (scenario-1)

**Comment by MaNe2020** [comment]
With new UI changes this is somewhat implemented. All future improvements should be added separately.

**Comment by MaNe2020** [comment]
This is already done in v0.13.0. Moving it for release

**Comment by chrisdiao** [comment]
@nishantswarup , could you please link the PR for this bug, please?
