### ISSUE TITLE
STOP processing does not work without refreshing the page (jupyter issue) but would be nice to see if it can be implemented differently

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#16]
@kekesimarti commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/334)

**Comment by chrisdiao** [comment]
Closing this case, this has been implemented 
https://glasswall-solutions.slack.com/archives/C020UU22BB4/p1627645498016700
