### ISSUE TITLE
Root of API should show the swagger page

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#18]
@DinisCruz commented on [Thu May 06 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/281)

i.e. instead of 
![image](https://user-images.githubusercontent.com/656739/117224825-c7ccef00-ae08-11eb-854a-42487a04ab11.png)

show 
![image](https://user-images.githubusercontent.com/656739/117224838-d1565700-ae08-11eb-83f1-d648fb0e7df5.png)

**Comment by MaNe2020** [comment]
This is an easy fix that just needs to open Swagger page on `localhost:port` instead of `localhost:port/docs`

**Comment by chrisdiao** [comment]
This has been included in v0.9.0 release
