### ISSUE TITLE
When setting #threads is used and does it need to be done for clear, load, set IPs or just start

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#2]
@kekesimarti commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/339)

**Comment by MaNe2020** [comment]
This is implemented on v0.13.0

**Comment by chrisdiao** [comment]
@nishantswarup , could you please link the PR for this bug, please?
