### ISSUE TITLE
Error when accessing dev_notebooks from Hugo

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#21]
@MaNe2020 commented on [Fri May 07 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/306)

Open Hugo (localhost:8004 or IP:1313) navigate to Servers>Jupyter and select dev notebooks
Getting empty page 
![image (10)](https://user-images.githubusercontent.com/70108899/117458130-39f91d00-af4a-11eb-9a75-4ecdc027bf7d.png)

---

@GINAGC commented on [Fri May 07 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/306#issuecomment-834503269)

@gmuditdce can you take a look to this issue please?

**Comment by gmuditdce** [comment]
yes @GINAGC checking this now.

**Comment by gmuditdce** [comment]
@MaNe2020  @GINAGC  Raised PR https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/366 for this-

![Screenshot from 2021-05-18 17-22-18](https://user-images.githubusercontent.com/71660612/118646386-c2ef3e80-b7fd-11eb-912a-d99b28c2af2d.png)

**Comment by MaNe2020** [comment]
@kekesimarti @gmuditdce I tested this on latest code from develop branch.
This is now fixed. Page (Servers>Jupyter) is displayed correctly and links from the page are accessible and once clicked opened in new tab. 

We can move this ticket in corresponding state.
