### ISSUE TITLE
Dev notebook for creating folder with clean files needs modifications

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#22]
@MaNe2020 commented on [Fri May 07 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/307)

It needs some indication that files are coping and also as sudo priv is needed for operations if folder does not exist and it does not have right permissions set it will not copy them 
![image (11)](https://user-images.githubusercontent.com/70108899/117458428-96f4d300-af4a-11eb-93a8-7539469d54d5.png)

---

@GINAGC commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/307#issuecomment-839479697)

@samarthdd can you take this please?

---

@samarthdd commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/307#issuecomment-839526567)

yes on it

**Comment by samarthdd** [comment]
this is fixed

**Comment by asloman** [comment]
<b>Posted By: Jamie Pool</b> <br/> <p>Already Closed</p>
