### ISSUE TITLE
Threat intelligence report not showing the total

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#23]
@Lestat06 commented on [Fri May 07 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/308)

It is showing the unique instances of risk level, instead of the total
![2k-threatLVL](https://user-images.githubusercontent.com/6232283/117460190-89404d00-af4c-11eb-81e4-d2efab2b1609.png)

---

@GINAGC commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/308#issuecomment-839479278)

@MaNe2020 can you take a look at this?

---

@MaNe2020 commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/308#issuecomment-839660301)

@GINAGC this is related to issue @samarthdd is working on.https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/322 or https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/263

@Lestat06 @GINAGC we can close this one as there are 2 other that are connected to this.

**Comment by kekesimarti** [comment]
It's a duplicate. I'm closing it.

**Comment by asloman** [comment]
<b>Posted By: Jamie Pool</b> <br/> <p>Already Closed</p>
