### ISSUE TITLE
Clear analysis_json data

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#24]
@MaNe2020 commented on [Mon May 10 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/322)

when we create Threat Analysis dashboard that uses analyse_json, when data are cleared, this dashboard always stays, it does not get updated. I suspect it is due to fact we do not have timestamp field there and that is required so Kibana can parse it. 

Find a way to clean analysis_json

---

@MaNe2020 commented on [Tue May 11 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/322#issuecomment-838289330)

@samarthdd @GINAGC I marked this as P1 as per daily meeting comments from today

---

@MaNe2020 commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/322#issuecomment-839666943)

video that show the issue in action: https://www.loom.com/share/c5ed52cf85a847a7a0a993088a3c0526

**Comment by samarthdd** [comment]
@MaNe2020 can you retest this from develop branch

**Comment by MaNe2020** [comment]
@samarthdd will test it out but at the moment I opened this issue: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/33
and this one can probably interfere with testing this correctly.

**Comment by MaNe2020** [comment]
This one is tested as part of another issue. It is fixed so will close this one.
