### ISSUE TITLE
Investigate GW SDK err "Report xml not exist for file"

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#25]
@MaNe2020 commented on [Tue May 11 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/326)

This is intermittent issue but during file processing file does not end up processed successfully due to "Report xml not exist for file".
If flow is retried it can end up build successfully but the question is what was wrong at the first place. 

---

@GINAGC commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/326#issuecomment-839476365)

@MaNe2020 please add a sample file for this to be duplicated. 

---

@MaNe2020 commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/326#issuecomment-839703841)

@GINAGC the thing with this one is that is can happen to any file. Here is one I had the issue, but on re-run and re-try this went smoothly
[CalcTest.xls](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6465860/CalcTest.xls)

---

@GINAGC commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/326#issuecomment-839838684)

@mohitsengarr can you take a look to this?

---

@mohitsengarr commented on [Mon May 17 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/326#issuecomment-842037162)

@MaNe2020 Can i know the endpoint please?

CC: @GINAGC 

---

@GINAGC commented on [Mon May 17 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/326#issuecomment-842527274)

@MaNe2020 to confirm endpoint.

**Comment by GINAGC** [comment]
@kekesimarti this is cloud sdk defect, this did not had to be moved.

**Comment by asloman** [comment]
<b>Posted By: Jamie Pool</b> <br/> <p>Already Closed</p>
