### ISSUE TITLE
not supported copied to todos

### ISSUE THREAD

**Issue by samarthdd** [filetrust/cdr-plugin-folder-to-folder-bugs#28]
new bug : When processed large number of files, few not supported files were in todo with error message  "The file type is not currently supported", on triggering retry  workflow, they got moved to not supported

**Comment by MaNe2020** [comment]
Duplicate with this one: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/46
But as #46 has more details I will close this one.
