### ISSUE TITLE
Dashboards list not loaded on VM initial startup

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#33]
Kibana Dashboards not loaded.
Steps to reproduce:
1. Deploy CDR Plugin
2. Navigate to Workflow/folder-to-folder
3. Verify Kibana Dashboards display

After step 3, list of Kibana Dashboards avl should be shown.
Instead there is "Create new Dashboard" interface. 

List of Dashboards should be avl from the start.

**Comment by MaNe2020** [comment]
@chrisdiao this one should have highest priority and should be fixed ASAP.

**Comment by GINAGC** [comment]
@MaNe2020 do we have a workaround for this? is this a blocker? if yes, it should be P0

**Comment by MaNe2020** [comment]
We have a workaround. Dashboards can be imported manually.
Most of ppl doing testing does that, but it is not straight forward way for others.

**Comment by GINAGC** [comment]
Thank you @MaNe2020. Then this one should stay for July and we should try to solve it in sprint 1.

**Comment by ggrig** [comment]
Here is how test_Dashboard.py works

![image](https://user-images.githubusercontent.com/26714598/124342191-3e9d2300-dbd3-11eb-85f6-bb589818a138.png)

The reason we pass it in GitHub actions is that the test gets skipped because of missing ES/Kibana deployment

**Comment by MaNe2020** [comment]
Dashboards are now loaded on startup.
@ggrig amazing job. Thanks for finally fixing this.
Moving for release.

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
