### ISSUE TITLE
 Crashed main loop

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#36]
1. Who reported the bug: Dinis
2. More context of the bug: This happened when there were no valid endpoints
3. Proofs of the bug:
![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/3ff875aa-4682-4085-a63f-8588f3206792)

![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/93f3ac05-6465-4ba6-b4f7-1b78583ec43c)

![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/7acb8a33-7549-42cd-aff9-197372fc51af)

**Comment by ggrig** [comment]
This has been fixed in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/399
