### ISSUE TITLE
Running test set jp-test causes crash in workflow cluster

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/cdr-plugin-folder-to-folder-bugs#37]
**Repro Steps:**
- Access workflow UI
- Check IPs are correctly set
- Navigate to f2f workflow
- Set base directory to desired test set
- Ensure any existing data is cleared
- Load files for testing
- Once files have loaded click 'Start Processing'

**Expected Result:**
- Workflow cluster should send all files in data set to sdk cluster for processing

**Actual Result:**
- Workflow cluster starts sending the files to sdk machine but crashes during processing
- This error is seen when crash occurs
![2021-05-12_15h32_20](https://user-images.githubusercontent.com/60877176/118996793-15586880-b980-11eb-826b-a156f96e60b1.png)
- The UI becomes unusable (cannot load anything using the APIs such as starting a different scenario or checking processing status)
- Cannot load the swagger page to run any API calls

In order to get the workflow cluster back into a working state you must ssh into the workflow cluster machine and run the following commands:
`sudo docker-compose down`

`sudo docker-compose up --build --force -d`

**NB** The data set can be found on the following AWS Account: **GlasswallAWSCloudSDK-Perf** (343259504932) at this location: **s3://cdr-plugin-perf-testdata/jp-test/**

**Comment by DinisCruz** [comment]
@jpoolGW can you try to create the smallest data set that reliable replicates the issue?

**Comment by chrisdiao** [comment]
@MaNe2020 @dpatel7, could you please review and confirm if this is still happening?

**Comment by MaNe2020** [comment]
@chrisdiao last time I checked it did not happen, let me verify one more time today and if it is not happening I will go ahead and close it.

**Comment by chrisdiao** [comment]
Thaank you @MaNe2020 !

**Comment by MaNe2020** [comment]
@chrisdiao this is no longer an issue. I will close it.
Tested on CDR Plugin v0.12.5
