### ISSUE TITLE
Start processing is loading files even if files have been loaded

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#38]
Previously the flow (from Hugo) was CLEAR, LOAD and START. As files have been loaded pressing START will start the processing.
From v0.6.4, pressing START will again LOAD or set files to initial state.

So or LOAD is not needed anymore or `start processing` is implemented incorrectly

**Comment by ggrig** [comment]
@MaNe2020 
At that time some recalculations were introduced to make sure that the rebuild process starts with correct counters
This has been optimized in v0.8.6 so the issue must be resolved there

**Comment by MaNe2020** [comment]
Duplicate of: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/405
