### ISSUE TITLE
Renaming file status

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#39]
`the file type is not currently supported`   --->   `file type not supported`
`unable to clean file`                                  --->   `failed to rebuild`
`the original file has been cleaned`           --->    `rebuild successfully`
`the original file was cleaned`                   --->     `original file is safe`

@dpatel7 pls check this naming

**Comment by dpatel7** [comment]
@MaNe2020 Look good

**Comment by MaNe2020** [comment]
This is done.
