### ISSUE TITLE
Box where we set base dir is not fixed it should be and also scroll bars should be removed both from that box and also output box next to it

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#4]
@kekesimarti commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/337)

**Comment by MaNe2020** [comment]
This is ready for release. Was done even on v0.13.0

**Comment by chrisdiao** [comment]
@nishantswarup , could you please link the PR for this bug, please?
