### ISSUE TITLE
Wrong Version Number appearing in health check 

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-folder-to-folder-bugs#40]
Repro Step 

- Navigate to https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/2684909979?check_suite_focus=true to get the version number  which is v.0.8.8
![image](https://user-images.githubusercontent.com/61416876/119974964-371fa400-bfad-11eb-8a22-065c24cd100e.png)
- Navigate to https://github.com/filetrust/cdr-plugin-folder-to-folder/actions/runs/882261324 to get the latest AMI ID for example eu-west-1: ami-0367280a73f5341de  
- Start EC2 machine using that AMI
- Navigate to http://localhost:8000/docs#/Health%20Checks/version_version_get and check the version which should be v.0.8.8 

But we see version v.0.8.7 
![2021-05-28_11h58_44](https://user-images.githubusercontent.com/61416876/119975475-d0e75100-bfad-11eb-982e-91306a09ebc1.png)

**Comment by chrisdiao** [comment]
This is already fixed in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/465
