### ISSUE TITLE
INC-1 - can't ssh to VM exported by ci/cd

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-folder-to-folder-bugs#44]
## Incident Response Team:

**Incident First Responder -** Maria
**Incident Manager-** 
**Incident communicator/reporter-**

## Tasks:

- [ ] T1. Assign Incident Response Team Roles
- [ ] T2. Start Slack Channel with Incident Name and mobilise team<br>
- [ ] T3. Determine incident severity (see table)
- [ ] T4. Open a Github incident issue<br>
- [ ] T5. Identify immediate steps to prevent further harm to the Glasswall assets<br>
- [ ] T6. Identify steps necessary to regain or ensure business continuity<br>
- [ ] T7. Identify next steps – update policies, processes and identify controls
- [ ] T8. Write Summary to PM and Dinis<br>

## Questions:

- [ ] Q1. Note Version details for Application under investigation<br>
- [ ] Q2. What is the impact?<br>
- [ ] Q3. What caused the outage?<br>
- [ ] Q4. What company asset(s) are involved?<br>
- [ ] Q5. Is business continuity ensured and if not, how do we enable it ASAP?<br>
- [ ] Q6. Do we have a disaster recovery plan and how do we put it into action?<br>
- [ ] Q7. What are the next steps in preparation for future incidents?<br>
- [ ] Q8. Has a bug been reported and is it scheduled for a fix?<br>
- [ ] Q9. What is the incident resolution?<br>

**Comment by MaNe2020** [comment]
@dpatel7 what actions should we take on this one?

**Comment by dpatel7** [comment]
@MaNe2020 start filling the answer to above question

**Comment by dpatel7** [comment]
@MaNe2020 can you manage above incidence and start answering the question?

**Comment by MaNe2020** [comment]
Q1. CDR F2F v0.8.8
 Q2. Cannot ssh/login to CDR Plugin
 Q3. VM password not set/shared correctly
 Q4. -
 Q5. Business continuity is ensured 
 Q6. No at that moment. 
 Q7. Document the process of setting the strong password on gitHub and name main stakeholders. 
 Q8. There was immediate fix and bug was not created. 
 Q9. Password was recreated and issue was resolved. 

@dpatel7 what should be next step?
I do not recall we defined after the questions are answered who assigns issue to Manager and who should pick up this from here.

**Comment by MaNe2020** [comment]
@chrisdiao this incident can be assigned further on to incident manager.
All actions from my side are done.

**Comment by michaelhidalgo** [comment]
Hey folks, I have two follow up questions to understand the context of the issue:

- Is SSH access required after all?
- If so,  who manages the SSH key or is it username/password-based?
- If so, how are we sharing the ssh key?
- where is it stored?

**Comment by MaNe2020** [comment]
Hi @michaelhidalgo 

- ssh is required as we cannot access Plugin directly with IP:PORT and we need to forward the ports 
- it is password based (no keys) and passwords are based on git hub secrets, created by admin and shared
- password is stored in passbolt

**Comment by MaNe2020** [comment]
We haven't done proper incident cycle with this one but it is fixed long ago and as an incident should be close.
