### ISSUE TITLE
All not supported files are not marked on the first processing

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#46]
1. Run files processing (ex. govUk dataset)
2. After processing is done, do the retry workflow (run it again)

All not supported files should be detected and marked as such after the step 1.
But it happens that during the retry, they keep being detected.

Below are the screenshots of 6 runs of govUk dataset. The runs 2-6 are all retries. 
Number of `not supported files` goes from 333 in first run to 494 in 6th.
That means that 1/3 of all not supported files was not marked/detected on the first processing.

All `not supported files` should be marked as such on the first run and the new files should not come up on retry. 

**Run 1** 
![run#1](https://user-images.githubusercontent.com/70108899/120939457-820d8a00-c718-11eb-874d-3501eb3c9c33.PNG)

**Run 2**
![run#2](https://user-images.githubusercontent.com/70108899/120939466-8c2f8880-c718-11eb-9152-aabe26730b94.PNG)

**Run 3**
![run#3](https://user-images.githubusercontent.com/70108899/120939475-981b4a80-c718-11eb-9b45-9e2e8817e039.PNG)

**Run 4**
![run#4](https://user-images.githubusercontent.com/70108899/120939489-a1a4b280-c718-11eb-96b1-5d68066daea2.PNG)

**Run 5**
![run#5](https://user-images.githubusercontent.com/70108899/120939504-a9fced80-c718-11eb-987f-9cbe8cd7cecd.PNG)

**Run 6**
![run#6](https://user-images.githubusercontent.com/70108899/120939512-b2552880-c718-11eb-961c-f8e43357c938.PNG)

**Comment by MaNe2020** [comment]
@chrisdiao this should be fixed soon as, functionality wise should work from scratch.

**Comment by GINAGC** [comment]
@rajmbcoderx can you review this one too?

**Comment by rajmbcoderx** [comment]
@GINAGC will look into this

**Comment by rajmbcoderx** [comment]
@MaNe2020 : Do you have some sample files which were marked as unsupported and later were being processed properly?

and from where can I download the govuk files?

**Comment by MaNe2020** [comment]
@rajmbcoderx basically any dataset. 
Check here: https://github.com/k8-proxy/data-sets
For govUK:
- subset of 1000 files (that should be good to use as it can be executed in short period of time):  s3://cdr-plugin-test-files/1000
- govUk: https://k8-mass-download.s3.eu-west-2.amazonaws.com/gov_Files.zip

**Comment by rajmbcoderx** [comment]
@MaNe2020 Can you please check again on this issue?

**Comment by MaNe2020** [comment]
@rajmbcoderx I think the issue here is that if SDK fails during the processing it will marked files as failed (as it was not able to process them). It is not related to flags, as if SDK is not working everything will be failed.
And the issue is probably happen for large dataset.
Not sure if we can say this is issue at all.
Will close it
