### ISSUE TITLE
INC-2- Minio go sdk connection refused error/RabbitMQ issue when run with more threads from CDR f2f

### ISSUE THREAD

**Issue by samarthdd** [filetrust/cdr-plugin-folder-to-folder-bugs#50]
Incident Response Team:

Incident First Responder - Samarth
Incident Manager-
Incident communicator/reporter-

## Tasks:

- [ ] T1. Assign Incident Response Team Roles
- [ ] T2. Start Slack Channel with Incident Name and mobilise team<br>
- [ ] T3. Determine incident severity (see table)
- [ ] T4. Open a Github incident issue<br>
- [ ] T5. Identify immediate steps to prevent further harm to the Glasswall assets<br>
- [ ] T6. Identify steps necessary to regain or ensure business continuity<br>
- [ ] T7. Identify next steps – update policies, processes and identify controls
- [ ] T8. Write Summary to PM and Dinis<br>

## Questions:

- [ ] Q1. Note Version details for Application under investigation<br>
- [ ] Q2. What is the impact?<br>
- [ ] Q3. What caused the outage?<br>
- [ ] Q4. What company asset(s) are involved?<br>
- [ ] Q5. Is business continuity ensured and if not, how do we enable it ASAP?<br>
- [ ] Q6. Do we have a disaster recovery plan and how do we put it into action?<br>
- [ ] Q7. What are the next steps in preparation for future incidents?<br>
- [ ] Q8. Has a bug been reported and is it scheduled for a fix?<br>
- [ ] Q9. What is the incident resolution?<br>

**Comment by samarthdd** [comment]
we had one session on friday and today for minio-sdk troubleshooting and fixing.

Friday we had issues in processing queue and it is fixed today ( after srv ).

Today we saw adaptation queue failure/connection refused error when we use 50 threads or more ( before srv )

Later after troubleshooting with Himamshu Mahmoud and Haitham, found out that on putting more threads, proxy-rest-api 
crashes /restarts due to cpu limit 500m.

The reason is something related to rabbitMQ since new Q will be created every time.

The workaround is increasing cpu to 2000m in proxy-rest-api.

Currently we have stable version of minio-sdk with limitation of 25 threads on cdr f2f.

The  fix or i can say fine tuning can be done by creating and keeping 2 queues, one for producer and one for consumer according to Mahmoud.

**Comment by dpatel7** [comment]
@samarthdd can you add yourself as a incident manager for this incident and start answering the question above and check them once is done

**Comment by samarthdd** [comment]
@dpatel7 
Here is the summary.

the issue was happening in request processing queue since a new queue was creating everytime a request made and due to high traffic in minio-sdk, the queue was breaking

Now currently it is modified only one queue and this issue is resolved in version 0.2.0 ( cs-k8s-api ) onwards


Now we are seeing one more issue/ scenario when run with 50+ threads.

This is mainly due to resource limitation, 
Current resource allocated for  rebuild-api is 500m 
with more than 50 threads CPU of rebuild-api reaches 100% and it restarts and things starts breaking.

This is not an issue but a limitation. This is related to fine tuning of solution. @mohitsengarr and Mahmoud is working on this to fine tune it in later stage.

We can close this issue

**Comment by samarthdd** [comment]
In summary,

the RabbitMq issue is resolved now

We have resource limitation now. It is also necessary to fine tune the solution to work with limited resource.

**Comment by samarthdd** [comment]
Here is the manual steps required to resolve this issue for 50 threads

https://docs.google.com/document/d/1pKE9TO_iJjq1yINhVnOIBsbXFjUV2W9H56Ni130wgSo

This will be automated in next release

**Comment by GINAGC** [comment]
this is done from latest release on minio version.
