### ISSUE TITLE
Allow to enter port in Hugo set IP page

### ISSUE THREAD

**Issue by samarthdd** [filetrust/cdr-plugin-folder-to-folder-bugs#56]
Here in Hugo there should be option to enter port as well, since now port is changed to 80/443

<img width="1436" alt="Screenshot 2021-06-10 at 12 37 40 PM" src="https://user-images.githubusercontent.com/64204445/121480700-f716e300-c9e8-11eb-985c-eb7f9b7b153d.png">

**Comment by chrisdiao** [comment]
@MaNe2020 @dpatel7 , could you please confirm if this is tested?

**Comment by MaNe2020** [comment]
@samarthdd @chrisdiao I can verify that new field is added 
![image](https://user-images.githubusercontent.com/70108899/121874537-baf4c280-cd07-11eb-9500-d126b962c0f8.png)

But I am not sure about functionality. 
If I set 443 port to existing IP it will not be added. 
So it looks like port is automatically pulled or additional configuration is needed
![image](https://user-images.githubusercontent.com/70108899/121874867-11fa9780-cd08-11eb-9f6a-2040e4003a4a.png)

**Comment by samarthdd** [comment]
@MaNe2020 
The port is nothing but GW SDK port
Before it was 8080. Now it is 80 ( it will be 443 later when DNS and cert is configured )

**Comment by kekesimarti** [comment]
@samarthdd please add a step-by-step tutorial on how to test it.

**Comment by samarthdd** [comment]
ok This feature is added because previously gw cloud sdk was listening to 8080 port. Now it is changed to port 80/443

Step to configure

1. Make sure your gw cloud sdk is working either from swagger UI  of sdk or from Postman
As you can see, IP is 54.216.188.250 and port is 80 here ( since its http )

<img width="1440" alt="Screenshot 2021-06-14 at 5 20 41 PM" src="https://user-images.githubusercontent.com/64204445/121888305-754eee80-cd35-11eb-8ea7-cf05b8543895.png">

2. Open Hugo website and navigate to Set Ip screen

Enter IP and port . In this case IP is 54.216.188.250 and port is 80

Note : if you enter multiple IPs, ports should be common. If you have multiple IPs with different ports, use endpoint
"/configuration/configure_gw_sdk_endpoints/" from swagger


<img width="984" alt="Screenshot 2021-06-14 at 5 21 16 PM" src="https://user-images.githubusercontent.com/64204445/121888424-99123480-cd35-11eb-9199-c0570d63ce6e.png">

3. Check output of set IPs

If mentioned IP is listening in mentioned port and sdk health is ok, then the IP will be assigned as shown below. 

If its not working, it will simply consider it as invalid and dont add to list of valid IPs 
<img width="1056" alt="Screenshot 2021-06-14 at 5 21 32 PM" src="https://user-images.githubusercontent.com/64204445/121888652-e0002a00-cd35-11eb-9f1d-800d4275c81b.png">

**Comment by chrisdiao** [comment]
@MaNe2020 , could you please check if the said information is enough?

**Comment by MaNe2020** [comment]
@samarthdd @ggrig for me it looks like there is some place that 8080 port is encoded and I cannot change it.
Also @nishantswarup this part has to be added to new UI.

**Comment by MaNe2020** [comment]
This is removed from this release as fix is needed.
Previous merge is reverted.
@chrisdiao pls assign to dev. I will move it to inProgress.

**Comment by MaNe2020** [comment]
@chrisdiao I think this is done even in this release.
But can we use this issue to set 80 as default port instead 8080.

**Comment by chrisdiao** [comment]
This has been included in the v0.12.0 release
