### ISSUE TITLE
INC-5: GitHub Actions broken pipeline

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#57]
## Questions:

- [X] Q1. Note Version details for Application under investigation: **CDR Plugin v0.10.0**<br>
- [X] Q2. What is the impact? **Cannot build AMI/OVA for the release**<br>
- [X] Q3. What caused the outage? **Broken shell script**<br>
- [X] Q4. What company asset(s) are involved? **/**<br>
- [X] Q5. Is business continuity ensured and if not, how do we enable it ASAP? **Business continuity is ensured**<br>
- [X] Q6. Do we have a disaster recovery plan and how do we put it into action? **Script fix**.<br>
- [X] Q7. What are the next steps in preparation for future incidents? **Find a way to test pipeline before doing the release so we do not have it broken.**<br>
- [X] Q8. Has a bug been reported and is it scheduled for a fix? **Reported internally.** [PR for issue created](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/482/files#diff-5732da6cfbeb3edf88be938be030fa589d17ce7fff27777d600443bfe20c6f1fR1)<br>
- [X] Q9. What is the incident resolution? N/A<br>

**Comment by MaNe2020** [comment]
AMI was successfully build on develop: https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/2831739023?check_suite_focus=true

@chrisdiao I would like to verify this on main also after the release. So would not close it still, maybe just mark it "For Release".

**Comment by chrisdiao** [comment]
this has been included in the released
