### ISSUE TITLE
Running pre-processor twice without a clean up results wrong counters in Status.json

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder-bugs#58]
@ggrig commented on [Mon Jun 14 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/496)

Expected result: the counters should not change if no file is added
Actual result: "files_copied" and "duplicate_files" get increased every time pre-processing is run without adding new files to HD1

![image](https://user-images.githubusercontent.com/26714598/121860787-42dbcc00-cd0a-11eb-9fce-d07cfc937235.png)
![image](https://user-images.githubusercontent.com/26714598/121860930-66067b80-cd0a-11eb-979e-cfee30015a87.png)
![image](https://user-images.githubusercontent.com/26714598/121861090-9221fc80-cd0a-11eb-8a9d-3f4a845e27b1.png)

**Comment by kekesimarti** [comment]
@ggrig Please include a unit test and an integration test. Also, please include a few notes for the QA team. Thank you.

**Comment by ggrig** [comment]
Unit test has been added to the PR
Integration test will be added to https://github.com/filetrust/cdr-plugin-f2f-automation-tests with a different PR

**Comment by MaNe2020** [comment]
This is working as expected now: 
![image](https://user-images.githubusercontent.com/70108899/123618111-2d859800-d808-11eb-9a0e-75d4eab0dd80.png)
Moving it for Release

**Comment by chrisdiao** [comment]
This has been included in v0.13.0 release
