### ISSUE TITLE
Minio Server not avl on 0.10.5

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#59]
1. Spin CDR Plugin VM (or start it from local)
2. Navigate to Minio (localhost:9000 or localhost:<PORT FORWARD>)

Minio is not accessible after step 2

**Comment by chrisdiao** [comment]
fixed in [here](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/517)

**Comment by MaNe2020** [comment]
This is fixed with latest changes from develop.

**Comment by chrisdiao** [comment]
This has been included in release v0.12.0
