### ISSUE TITLE
Kibana Dashboards do not pick up new directory data and should (re)load - find a way to do this automatically without the need for (re)load

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#6]
@kekesimarti commented on [Wed May 12 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/335)

**Comment by ggrig** [comment]
Not clear if this still is an issue and what are the steps to reproduce it
Asked @MaNe2020 for details

**Comment by GINAGC** [comment]
Assigning to @MaNe2020 to provide more information.

**Comment by MaNe2020** [comment]
@ggrig this logic is different with the new UI.
I will close this one and in case smth similar appear will open new issue.
