### ISSUE TITLE
Cannot set goland SDK IP in CDR 

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#60]
Scenario 1
1. Access CDR Plugin
2. Set base dir
3. Navigate to set IPs, and enter manually golang SDK IP
Scenario 2
1. Navigate to CDR Plugin Swagger page
2. Execute API `/configuration/configure_gw_sdk_endpoints/` and provide golang SDK IP with port 80

Expected results: After step 3 in scenario 3, and step 2 in scenario 2, goland SDK IP is set correctly
Actual result: Not able to set SDK IP.
In scenario 1, nothing happens and the output is default LB or SDK IPs from AWS
In scenario 2, output is as on the screenshot 
![image](https://user-images.githubusercontent.com/70108899/122576681-38933800-d052-11eb-9171-11a5844ebaf3.png)

**Comment by MaNe2020** [comment]
Here is the video of the issue: https://www.loom.com/share/06645eb54bf6485a979255a135c4a483

**Comment by gmuditdce** [comment]
@MaNe2020 @GINAGC issue is the ports being tried above are all blocked for access from the machine running f2f.
@samarthdd has opened 8080 (where the rebuild sdk is running) for public use
@MaNe2020 can try now it should work ok.

**Comment by MaNe2020** [comment]
The issue was due to wrong port permissions.
It is resolved and I will close it.
