### ISSUE TITLE
API for CDR Plugin version returns empty string

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#61]
1. Deploy CDR 
2. Navigate to Swager
3. Go to /version API and execute

After step 3 empty CDR Plugin version is return instead of corresponding build.
![image](https://user-images.githubusercontent.com/70108899/122587896-b2c9b980-d05e-11eb-94c7-78411a86c5e5.png)

This error is also present during `docker-compose up` as it notifies that CDR Plugin version is not avl and that empty string will be used.

**Comment by MaNe2020** [comment]
@chrisdiao this should be simple but very important fix. Leaving it as P1.

**Comment by chrisdiao** [comment]
This will be included in release v0.15.0 as @dpatel7 confirmed that is is working fine

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
