### ISSUE TITLE
Root folder issue

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder-bugs#67]
F2F Plugin returns root_folder with scenario name from the backend and hence UI cannot dynamically build the folder list. F2F Plugin should return the base directory as the root folder so that UI can use that information instead of hardcoding that information

**Comment by MaNe2020** [comment]
@rajmbcoderx pls comment is this is fixed. Will assign it to you.

**Comment by rajmbcoderx** [comment]
@MaNe2020 I am still working on this issue. I should be able to close this issue by today.

**Comment by MaNe2020** [comment]
@chrisdiao @rajmbcoderx this one is still not fixed. Moving it to inProgress
![image](https://user-images.githubusercontent.com/70108899/124452963-2f5ed680-dd87-11eb-9ce9-9165ca26fad9.png)

**Comment by MaNe2020** [comment]
Retested after removing docker image. Works now.

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
