### ISSUE TITLE
Make sure that the ES server is up before the API server starts

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder-bugs#7]
@kekesimarti commented on [Wed May 05 2021](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/275)

For more context please [check this PR](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/248#discussion_r626429672)
![image](https://user-images.githubusercontent.com/79467690/117134698-2f058780-ada6-11eb-85f0-1bbb8b18bb83.png)

**Comment by MaNe2020** [comment]
Leaving this one as it is. @chrisdiao pls check with dev team as this is maybe fixed already. If not they can confirm how much it takes to do this one.

**Comment by rajmbcoderx** [comment]
@chrisdiao / @MaNe2020 This issue has already been fixed. This ticket should be closed.
