### ISSUE TITLE
INC-8- Minio not working on latest from develop

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#72]
Spin CDR Plugin VM (or start it from local)
Navigate to Minio (localhost:9000 or localhost:)
Minio is not accessible after step 2

- [X] Q1. Note Version details for Application under investigation: **CDR Plugin v0.14.7**<br>
- [X] Q2. What is the impact? **Cannot access Minio**<br>
- [X] Q3. What caused the outage? **Minio port not accessible**<br>
- [X] Q4. What company asset(s) are involved? **/**<br>
- [X] Q5. Is business continuity ensured and if not, how do we enable it ASAP? **Business continuity is ensured**<br>
- [X] Q6. Do we have a disaster recovery plan and how do we put it into action? **N/A**.<br>
- [X] Q7. What are the next steps in preparation for future incidents? **Find a way to test pipeline before doing the release so we do not have it broken.**<br>
- [X] Q8. Has a bug been reported and is it scheduled for a fix? **Incident reported**<br>
- [X] Q9. What is the incident resolution? N/A<br>

**Comment by dpatel7** [comment]
@ggrig I can see when we try and access the minio is redirecting to different port. I will review above PR with old image tag

**Comment by MaNe2020** [comment]
This has been fixed. @ggrig thanks for taking care of this in short time.

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
